spring:
  application:
    name: broker-report-api

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/broker_report_db}
      database: broker_report_db

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: broker-report-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.rvneto.broker.report.dto"
        spring.json.use.type.headers: false

app:
  kafka:
    consumer:
      topic-order-events: order-events-v1
      topic-wallet-events: wallet-events-v1
      topic-asset-market-data: assets-market-data-v1

server:
  port: 8087

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
